######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 25 14:31:22 2018
######################################################################
QT += core gui widgets

TEMPLATE = app


TARGET = fun

FORMS +=

HEADERS += \
    $$PWD/viewer.h

SOURCES += \
    $$PWD/guiMain.cpp \
    $$PWD/viewer.cpp




